/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinellipichiumagazzino;

import javax.swing.JOptionPane;

/**
 *
 * @author Aureli Giulia, Martinelli Alessandra e Pichiu Florin
 */
public class FrmProdotto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProdotto.class.getName());

    /**
     * Creates new form FrmProdotto
     */
    public FrmProdotto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        pnlNuovoProdotto = new javax.swing.JPanel();
        lblNomeProdotto = new javax.swing.JLabel();
        txtNomeProdotto = new javax.swing.JTextField();
        lblPrezzoAcquisto = new javax.swing.JLabel();
        txtPrezzoAcquisto = new javax.swing.JTextField();
        lblPrezzoVendita = new javax.swing.JLabel();
        lblScortaIniziale = new javax.swing.JLabel();
        lblScortaMinima = new javax.swing.JLabel();
        txtScortaIniziale = new javax.swing.JTextField();
        txtScortaMinima = new javax.swing.JTextField();
        txtPrezzoVendita = new javax.swing.JTextField();
        btnAnnulla = new javax.swing.JButton();
        btnAggiungi = new javax.swing.JButton();
        pnlTitoloNuovoProdotto = new javax.swing.JPanel();
        lblNuovoProdotto = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiungi nuovo prodotto");

        pnlNuovoProdotto.setBackground(new java.awt.Color(246, 246, 246));

        lblNomeProdotto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblNomeProdotto.setLabelFor(txtNomeProdotto);
        lblNomeProdotto.setText("Nome prodotto");

        lblPrezzoAcquisto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblPrezzoAcquisto.setLabelFor(txtPrezzoAcquisto);
        lblPrezzoAcquisto.setText("P. Acquisto (€)");

        lblPrezzoVendita.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblPrezzoVendita.setLabelFor(txtPrezzoVendita);
        lblPrezzoVendita.setText("P. Vendita (€)");

        lblScortaIniziale.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblScortaIniziale.setLabelFor(txtScortaIniziale);
        lblScortaIniziale.setText("Scorta Iniziale");

        lblScortaMinima.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblScortaMinima.setLabelFor(txtScortaMinima);
        lblScortaMinima.setText("Scorta Minima");

        btnAnnulla.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnAnnulla.setText("Annulla");
        btnAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnullaActionPerformed(evt);
            }
        });

        btnAggiungi.setBackground(new java.awt.Color(102, 102, 255));
        btnAggiungi.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnAggiungi.setForeground(new java.awt.Color(255, 255, 255));
        btnAggiungi.setText("Aggiungi");
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNuovoProdottoLayout = new javax.swing.GroupLayout(pnlNuovoProdotto);
        pnlNuovoProdotto.setLayout(pnlNuovoProdottoLayout);
        pnlNuovoProdottoLayout.setHorizontalGroup(
            pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNomeProdotto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNomeProdotto, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                            .addComponent(btnAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(btnAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNuovoProdottoLayout.createSequentialGroup()
                            .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblScortaIniziale)
                                .addComponent(txtScortaIniziale, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPrezzoAcquisto)
                                .addComponent(txtPrezzoAcquisto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)
                            .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPrezzoVendita)
                                .addComponent(txtScortaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblScortaMinima)
                                .addComponent(txtPrezzoVendita, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlNuovoProdottoLayout.setVerticalGroup(
            pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNomeProdotto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezzoAcquisto)
                    .addComponent(lblPrezzoVendita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezzoAcquisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrezzoVendita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScortaIniziale)
                    .addComponent(lblScortaMinima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScortaIniziale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtScortaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlTitoloNuovoProdotto.setBackground(new java.awt.Color(224, 224, 224));

        lblNuovoProdotto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        lblNuovoProdotto.setText("Nuovo prodotto");

        javax.swing.GroupLayout pnlTitoloNuovoProdottoLayout = new javax.swing.GroupLayout(pnlTitoloNuovoProdotto);
        pnlTitoloNuovoProdotto.setLayout(pnlTitoloNuovoProdottoLayout);
        pnlTitoloNuovoProdottoLayout.setHorizontalGroup(
            pnlTitoloNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloNuovoProdottoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblNuovoProdotto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitoloNuovoProdottoLayout.setVerticalGroup(
            pnlTitoloNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloNuovoProdottoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNuovoProdotto)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitoloNuovoProdotto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNuovoProdotto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlTitoloNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bottone per chiudere la frame
     * @param evt 
     */
    private void btnAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnullaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAnnullaActionPerformed

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        if(controlloTextBox() || !controlloInt()){
            JOptionPane.showMessageDialog(this, "Inserisci tutti i dati corretamente", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int id = GestioneMagazzino.getMagazzino().getListaProdotti().size(),
        prezzoAcquisto = Integer.parseInt(txtPrezzoAcquisto.getText()), 
        prezzoVendita = Integer.parseInt(txtPrezzoVendita.getText()), 
        scortaIniziale = Integer.parseInt(txtScortaIniziale.getText()), 
        scortaMinima = Integer.parseInt(txtScortaMinima.getText());
        String nome = txtNomeProdotto.getText();
        svuotaTextBox();
        GestioneMagazzino.getMagazzino().registraProdotto(new Prodotto(id, nome, prezzoAcquisto, prezzoVendita, scortaIniziale, scortaMinima));
    }//GEN-LAST:event_btnAggiungiActionPerformed

    /**
     * Metodo per controllae se c'e' una textbox vuota
     * @return true se c'e' almeno una textbox vuota
     */
    public boolean controlloTextBox(){
        return txtPrezzoAcquisto.getText().isBlank() || txtPrezzoVendita.getText().isBlank() || txtScortaIniziale.getText().isBlank() || txtScortaMinima.getText().isBlank() || txtNomeProdotto.getText().isBlank();
    }
    /**
     * Metodo per controllare se le textbox contengono numeri
     * @return true se sono tutti numeri
     */
    public boolean controlloInt(){
        try {
        Integer.parseInt(txtPrezzoAcquisto.getText());
        Integer.parseInt(txtPrezzoVendita.getText());
        Integer.parseInt(txtScortaIniziale.getText());
        Integer.parseInt(txtScortaMinima.getText());
        return true;
    } catch (NumberFormatException e) {
        return false;
    } 
    }
    /**
     * Metodo per svuotare le textbox
     */
    private void svuotaTextBox(){
        txtNomeProdotto.setText("");
        txtPrezzoAcquisto.setText("");
        txtPrezzoVendita.setText("");
        txtScortaIniziale.setText("");
        txtScortaMinima.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmProdotto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblNomeProdotto;
    private javax.swing.JLabel lblNuovoProdotto;
    private javax.swing.JLabel lblPrezzoAcquisto;
    private javax.swing.JLabel lblPrezzoVendita;
    private javax.swing.JLabel lblScortaIniziale;
    private javax.swing.JLabel lblScortaMinima;
    private javax.swing.JPanel pnlNuovoProdotto;
    private javax.swing.JPanel pnlTitoloNuovoProdotto;
    private javax.swing.JTextField txtNomeProdotto;
    private javax.swing.JTextField txtPrezzoAcquisto;
    private javax.swing.JTextField txtPrezzoVendita;
    private javax.swing.JTextField txtScortaIniziale;
    private javax.swing.JTextField txtScortaMinima;
    // End of variables declaration//GEN-END:variables
}
