/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinellipichiumagazzino;

/**
 *
 * @author PICHIU.FLORIN
 */
public class FrmRifornisci extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRifornisci.class.getName());

    /**
     * Creates new form FrmProdotto
     */
    public FrmRifornisci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        pnlRifornimento = new javax.swing.JPanel();
        lblNomeProdotto = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblQuantita = new javax.swing.JLabel();
        txtQuantita = new javax.swing.JTextField();
        btnAnnulla = new javax.swing.JButton();
        btnConferma = new javax.swing.JButton();
        lblSaldoAttuale = new javax.swing.JLabel();
        pnlTitoloRifornimento = new javax.swing.JPanel();
        lblNuovaVendita = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiungi nuovo prodotto");

        pnlRifornimento.setBackground(new java.awt.Color(246, 246, 246));

        lblNomeProdotto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblNomeProdotto.setText("Nome prodotto: nome");

        lblID.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblID.setText("ID: 0");

        lblQuantita.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblQuantita.setLabelFor(txtQuantita);
        lblQuantita.setText("Quantità da vendere:");

        btnAnnulla.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnAnnulla.setText("Annulla");
        btnAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnullaActionPerformed(evt);
            }
        });

        btnConferma.setBackground(new java.awt.Color(102, 102, 255));
        btnConferma.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnConferma.setForeground(new java.awt.Color(255, 255, 255));
        btnConferma.setText("Conferma");

        lblSaldoAttuale.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblSaldoAttuale.setText("Saldo attuale: 0");

        javax.swing.GroupLayout pnlRifornimentoLayout = new javax.swing.GroupLayout(pnlRifornimento);
        pnlRifornimento.setLayout(pnlRifornimentoLayout);
        pnlRifornimentoLayout.setHorizontalGroup(
            pnlRifornimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRifornimentoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlRifornimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRifornimentoLayout.createSequentialGroup()
                        .addComponent(lblSaldoAttuale)
                        .addGap(125, 125, 125)
                        .addComponent(lblID)
                        .addGap(8, 8, 8))
                    .addGroup(pnlRifornimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNomeProdotto)
                        .addGroup(pnlRifornimentoLayout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(btnAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(btnConferma, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblQuantita)
                        .addComponent(txtQuantita, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlRifornimentoLayout.setVerticalGroup(
            pnlRifornimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRifornimentoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNomeProdotto)
                .addGap(18, 18, 18)
                .addGroup(pnlRifornimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoAttuale)
                    .addComponent(lblID))
                .addGap(18, 18, 18)
                .addComponent(lblQuantita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantita, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRifornimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConferma, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlTitoloRifornimento.setBackground(new java.awt.Color(224, 224, 224));

        lblNuovaVendita.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        lblNuovaVendita.setText("Nuova vendita");

        javax.swing.GroupLayout pnlTitoloRifornimentoLayout = new javax.swing.GroupLayout(pnlTitoloRifornimento);
        pnlTitoloRifornimento.setLayout(pnlTitoloRifornimentoLayout);
        pnlTitoloRifornimentoLayout.setHorizontalGroup(
            pnlTitoloRifornimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloRifornimentoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblNuovaVendita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitoloRifornimentoLayout.setVerticalGroup(
            pnlTitoloRifornimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloRifornimentoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNuovaVendita)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitoloRifornimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRifornimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlTitoloRifornimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlRifornimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bottone per chiudere la frame
     * @param evt 
     */
    private void btnAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnullaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAnnullaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRifornisci().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JButton btnConferma;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNomeProdotto;
    private javax.swing.JLabel lblNuovaVendita;
    private javax.swing.JLabel lblQuantita;
    private javax.swing.JLabel lblSaldoAttuale;
    private javax.swing.JPanel pnlRifornimento;
    private javax.swing.JPanel pnlTitoloRifornimento;
    private javax.swing.JTextField txtQuantita;
    // End of variables declaration//GEN-END:variables
}
