/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinellipichiumagazzino;

import java.util.ArrayList;

/**
 *
 * @author Aureli Giulia, Martinelli Alessandra e Pichiu Florin
 */
public class FrmStatistiche extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmStatistiche.class.getName());
    private Statistiche statistiche = new Statistiche(GestioneMagazzino.getMagazzino());
    /**
     * Creates new form FrmProdotto
     */
    public FrmStatistiche() {
        initComponents();
        aggiornaLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNuovoProdotto = new javax.swing.JPanel();
        lblPCostoso = new javax.swing.JLabel();
        lblPEconomico = new javax.swing.JLabel();
        lblProdottoMinVenduto = new javax.swing.JLabel();
        lblProdottoMaxVenduto = new javax.swing.JLabel();
        lblProdottoCostoso = new javax.swing.JLabel();
        lblProdottoEconomico = new javax.swing.JLabel();
        lblMaxVenduto = new javax.swing.JLabel();
        lblMinVenduto = new javax.swing.JLabel();
        btnAggiorna = new javax.swing.JButton();
        pnlTitoloNuovoProdotto = new javax.swing.JPanel();
        lblStatistiche = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistiche");
        setResizable(false);

        pnlNuovoProdotto.setBackground(new java.awt.Color(246, 246, 246));

        lblPCostoso.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPCostoso.setLabelFor(lblPCostoso);
        lblPCostoso.setText("Prodotto costoso");

        lblPEconomico.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPEconomico.setLabelFor(lblPEconomico);
        lblPEconomico.setText("Prodotto eco");

        lblProdottoMinVenduto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProdottoMinVenduto.setLabelFor(lblProdottoMinVenduto);
        lblProdottoMinVenduto.setText("MinVenduto");

        lblProdottoMaxVenduto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProdottoMaxVenduto.setLabelFor(lblProdottoMaxVenduto);
        lblProdottoMaxVenduto.setText("MaxVenduto");

        lblProdottoCostoso.setText("-");

        lblProdottoEconomico.setText("-");

        lblMaxVenduto.setText("-");

        lblMinVenduto.setText("-");

        btnAggiorna.setBackground(new java.awt.Color(102, 102, 255));
        btnAggiorna.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnAggiorna.setForeground(new java.awt.Color(255, 255, 255));
        btnAggiorna.setText("Aggiorna");
        btnAggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiornaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNuovoProdottoLayout = new javax.swing.GroupLayout(pnlNuovoProdotto);
        pnlNuovoProdotto.setLayout(pnlNuovoProdottoLayout);
        pnlNuovoProdottoLayout.setHorizontalGroup(
            pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProdottoCostoso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProdottoMaxVenduto)
                    .addComponent(lblPCostoso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaxVenduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProdottoMinVenduto)
                                    .addComponent(lblPEconomico))
                                .addGap(0, 31, Short.MAX_VALUE))
                            .addComponent(lblProdottoEconomico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMinVenduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuovoProdottoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        pnlNuovoProdottoLayout.setVerticalGroup(
            pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPCostoso)
                    .addComponent(lblPEconomico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdottoCostoso)
                    .addComponent(lblProdottoEconomico))
                .addGap(39, 39, 39)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdottoMaxVenduto)
                    .addComponent(lblProdottoMinVenduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxVenduto)
                    .addComponent(lblMinVenduto))
                .addGap(18, 18, 18)
                .addComponent(btnAggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnlTitoloNuovoProdotto.setBackground(new java.awt.Color(224, 224, 224));

        lblStatistiche.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        lblStatistiche.setText("Statistiche");

        javax.swing.GroupLayout pnlTitoloNuovoProdottoLayout = new javax.swing.GroupLayout(pnlTitoloNuovoProdotto);
        pnlTitoloNuovoProdotto.setLayout(pnlTitoloNuovoProdottoLayout);
        pnlTitoloNuovoProdottoLayout.setHorizontalGroup(
            pnlTitoloNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloNuovoProdottoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblStatistiche)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitoloNuovoProdottoLayout.setVerticalGroup(
            pnlTitoloNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloNuovoProdottoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblStatistiche)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitoloNuovoProdotto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNuovoProdotto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlTitoloNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiornaActionPerformed
        aggiornaLabel();
    }//GEN-LAST:event_btnAggiornaActionPerformed

    public void aggiornaLabel(){
        ArrayList<Prodotto> prodotti = statistiche.vediStatistiche();
        if(prodotti.get(0) == null) lblProdottoCostoso.setText("-");
        else lblProdottoCostoso.setText(prodotti.get(0).getNome() + ", costo: " + prodotti.get(0).getPrezzoVendita());
        if(prodotti.get(1) == null) lblProdottoEconomico.setText("-");
        else lblProdottoEconomico.setText(prodotti.get(1).getNome() + ", costo: " + prodotti.get(1).getPrezzoVendita());
        if(prodotti.get(2) == null) lblMaxVenduto.setText("-");
        else lblMaxVenduto.setText(prodotti.get(2).getNome() + ", quantita' venduta: " + prodotti.get(2).getProdottiVenduti());
        if(prodotti.get(3) == null) lblProdottoCostoso.setText("-");
        else lblMinVenduto.setText(prodotti.get(3).getNome() + ", quantita' venduta: " + prodotti.get(3).getProdottiVenduti());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmStatistiche().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiorna;
    private javax.swing.JLabel lblMaxVenduto;
    private javax.swing.JLabel lblMinVenduto;
    private javax.swing.JLabel lblPCostoso;
    private javax.swing.JLabel lblPEconomico;
    private javax.swing.JLabel lblProdottoCostoso;
    private javax.swing.JLabel lblProdottoEconomico;
    private javax.swing.JLabel lblProdottoMaxVenduto;
    private javax.swing.JLabel lblProdottoMinVenduto;
    private javax.swing.JLabel lblStatistiche;
    private javax.swing.JPanel pnlNuovoProdotto;
    private javax.swing.JPanel pnlTitoloNuovoProdotto;
    // End of variables declaration//GEN-END:variables
}
