/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinellipichiumagazzino;

/**
 *
 * @author Aureli Giulia, Martinelli Alessandra e Pichiu Florin
 */
public class FrmStatistiche extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmStatistiche.class.getName());

    /**
     * Creates new form FrmProdotto
     */
    public FrmStatistiche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        pnlNuovoProdotto = new javax.swing.JPanel();
        lblQuantitaProdottoCostoso = new javax.swing.JLabel();
        lblQuantitaProdottoEconomico = new javax.swing.JLabel();
        lblQuantitaProdottoMinVenduto = new javax.swing.JLabel();
        lblQuantitaProdottoMaxVenduto = new javax.swing.JLabel();
        lblProdottoCostoso = new javax.swing.JLabel();
        lblProdottoEconomico = new javax.swing.JLabel();
        lblMaxVenduto = new javax.swing.JLabel();
        lblMinVenduto = new javax.swing.JLabel();
        pnlTitoloNuovoProdotto = new javax.swing.JPanel();
        lblStatistiche = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiungi nuovo prodotto");

        pnlNuovoProdotto.setBackground(new java.awt.Color(246, 246, 246));

        lblQuantitaProdottoCostoso.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblQuantitaProdottoCostoso.setLabelFor(lblQuantitaProdottoCostoso);
        lblQuantitaProdottoCostoso.setText("Prodotto costoso");

        lblQuantitaProdottoEconomico.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblQuantitaProdottoEconomico.setLabelFor(lblQuantitaProdottoEconomico);
        lblQuantitaProdottoEconomico.setText("Prodotto eco");

        lblQuantitaProdottoMinVenduto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblQuantitaProdottoMinVenduto.setLabelFor(lblQuantitaProdottoMinVenduto);
        lblQuantitaProdottoMinVenduto.setText("MinVenduto");

        lblQuantitaProdottoMaxVenduto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblQuantitaProdottoMaxVenduto.setLabelFor(lblQuantitaProdottoMaxVenduto);
        lblQuantitaProdottoMaxVenduto.setText("MaxVenduto");

        lblProdottoCostoso.setText("Nome");

        lblProdottoEconomico.setText("Nome");

        lblMaxVenduto.setText("Nome");

        lblMinVenduto.setText("Nome");

        javax.swing.GroupLayout pnlNuovoProdottoLayout = new javax.swing.GroupLayout(pnlNuovoProdotto);
        pnlNuovoProdotto.setLayout(pnlNuovoProdottoLayout);
        pnlNuovoProdottoLayout.setHorizontalGroup(
            pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProdottoCostoso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQuantitaProdottoMaxVenduto)
                    .addComponent(lblQuantitaProdottoCostoso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaxVenduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantitaProdottoMinVenduto)
                                    .addComponent(lblQuantitaProdottoEconomico))
                                .addGap(0, 31, Short.MAX_VALUE))
                            .addComponent(lblProdottoEconomico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMinVenduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlNuovoProdottoLayout.setVerticalGroup(
            pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantitaProdottoCostoso)
                    .addComponent(lblQuantitaProdottoEconomico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdottoCostoso)
                    .addComponent(lblProdottoEconomico))
                .addGap(39, 39, 39)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantitaProdottoMaxVenduto)
                    .addComponent(lblQuantitaProdottoMinVenduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxVenduto)
                    .addComponent(lblMinVenduto))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pnlTitoloNuovoProdotto.setBackground(new java.awt.Color(224, 224, 224));

        lblStatistiche.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        lblStatistiche.setText("Statistiche");

        javax.swing.GroupLayout pnlTitoloNuovoProdottoLayout = new javax.swing.GroupLayout(pnlTitoloNuovoProdotto);
        pnlTitoloNuovoProdotto.setLayout(pnlTitoloNuovoProdottoLayout);
        pnlTitoloNuovoProdottoLayout.setHorizontalGroup(
            pnlTitoloNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloNuovoProdottoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblStatistiche)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitoloNuovoProdottoLayout.setVerticalGroup(
            pnlTitoloNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloNuovoProdottoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblStatistiche)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitoloNuovoProdotto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNuovoProdotto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlTitoloNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmStatistiche().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblMaxVenduto;
    private javax.swing.JLabel lblMinVenduto;
    private javax.swing.JLabel lblProdottoCostoso;
    private javax.swing.JLabel lblProdottoEconomico;
    private javax.swing.JLabel lblQuantitaProdottoCostoso;
    private javax.swing.JLabel lblQuantitaProdottoEconomico;
    private javax.swing.JLabel lblQuantitaProdottoMaxVenduto;
    private javax.swing.JLabel lblQuantitaProdottoMinVenduto;
    private javax.swing.JLabel lblStatistiche;
    private javax.swing.JPanel pnlNuovoProdotto;
    private javax.swing.JPanel pnlTitoloNuovoProdotto;
    // End of variables declaration//GEN-END:variables
}
