/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinellipichiumagazzino;

/**
 *
 * @author Aureli Giulia, Martinelli Alessandra e Pichiu Florin
 */
public class FrmStatistiche extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmStatistiche.class.getName());

    /**
     * Creates new form FrmProdotto
     */
    public FrmStatistiche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        pnlNuovoProdotto = new javax.swing.JPanel();
        btnProdottoCostoso = new javax.swing.JLabel();
        txtProdottoCostoso = new javax.swing.JTextField();
        btnProdottoEconomico = new javax.swing.JLabel();
        txtProdottoEconomico = new javax.swing.JTextField();
        btnProdottoMinVenduto = new javax.swing.JLabel();
        btnProdottoMaxVenduto = new javax.swing.JLabel();
        txtProdottoMaxVenduto = new javax.swing.JTextField();
        txtProdottoMinVenduto = new javax.swing.JTextField();
        btnAnnulla = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        pnlTitoloNuovoProdotto = new javax.swing.JPanel();
        lblStatistiche = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiungi nuovo prodotto");

        pnlNuovoProdotto.setBackground(new java.awt.Color(246, 246, 246));

        btnProdottoCostoso.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        btnProdottoCostoso.setLabelFor(txtProdottoCostoso);
        btnProdottoCostoso.setText("Prodotto costoso");

        btnProdottoEconomico.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        btnProdottoEconomico.setLabelFor(txtProdottoEconomico);
        btnProdottoEconomico.setText("Prodotto eco");

        btnProdottoMinVenduto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        btnProdottoMinVenduto.setLabelFor(txtProdottoMinVenduto);
        btnProdottoMinVenduto.setText("MinVenduto");

        btnProdottoMaxVenduto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        btnProdottoMaxVenduto.setLabelFor(txtProdottoMaxVenduto);
        btnProdottoMaxVenduto.setText("MaxVenduto");

        txtProdottoMaxVenduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdottoMaxVendutoActionPerformed(evt);
            }
        });

        btnAnnulla.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnAnnulla.setText("Annulla");
        btnAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnullaActionPerformed(evt);
            }
        });

        btnSalva.setBackground(new java.awt.Color(102, 102, 255));
        btnSalva.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnSalva.setForeground(new java.awt.Color(255, 255, 255));
        btnSalva.setText("Salva");

        javax.swing.GroupLayout pnlNuovoProdottoLayout = new javax.swing.GroupLayout(pnlNuovoProdotto);
        pnlNuovoProdotto.setLayout(pnlNuovoProdottoLayout);
        pnlNuovoProdottoLayout.setHorizontalGroup(
            pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtProdottoCostoso, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnProdottoCostoso, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNuovoProdottoLayout.createSequentialGroup()
                        .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProdottoMaxVenduto)
                            .addComponent(txtProdottoMaxVenduto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProdottoMinVenduto)
                            .addComponent(txtProdottoMinVenduto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProdottoEconomico)
                            .addComponent(txtProdottoEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlNuovoProdottoLayout.setVerticalGroup(
            pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnProdottoCostoso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProdottoCostoso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProdottoEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNuovoProdottoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnProdottoEconomico)))
                .addGap(27, 27, 27)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdottoMinVenduto)
                    .addComponent(btnProdottoMaxVenduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdottoMinVenduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdottoMaxVenduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(pnlNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pnlTitoloNuovoProdotto.setBackground(new java.awt.Color(224, 224, 224));

        lblStatistiche.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        lblStatistiche.setText("Statistiche");

        javax.swing.GroupLayout pnlTitoloNuovoProdottoLayout = new javax.swing.GroupLayout(pnlTitoloNuovoProdotto);
        pnlTitoloNuovoProdotto.setLayout(pnlTitoloNuovoProdottoLayout);
        pnlTitoloNuovoProdottoLayout.setHorizontalGroup(
            pnlTitoloNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloNuovoProdottoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblStatistiche)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitoloNuovoProdottoLayout.setVerticalGroup(
            pnlTitoloNuovoProdottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloNuovoProdottoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblStatistiche)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitoloNuovoProdotto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNuovoProdotto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlTitoloNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bottone per chiudere la frame
     * @param evt 
     */
    private void btnAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnullaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAnnullaActionPerformed

    private void txtProdottoMaxVendutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdottoMaxVendutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdottoMaxVendutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmStatistiche().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JLabel btnProdottoCostoso;
    private javax.swing.JLabel btnProdottoEconomico;
    private javax.swing.JLabel btnProdottoMaxVenduto;
    private javax.swing.JLabel btnProdottoMinVenduto;
    private javax.swing.JButton btnSalva;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblStatistiche;
    private javax.swing.JPanel pnlNuovoProdotto;
    private javax.swing.JPanel pnlTitoloNuovoProdotto;
    private javax.swing.JTextField txtProdottoCostoso;
    private javax.swing.JTextField txtProdottoEconomico;
    private javax.swing.JTextField txtProdottoMaxVenduto;
    private javax.swing.JTextField txtProdottoMinVenduto;
    // End of variables declaration//GEN-END:variables
}
